#!/usr/bin/env python3
#
# Copyright (C) 2006--2009,2019  Kipp C. Cannon
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#


import math
import matplotlib
matplotlib.rcParams.update({
	"font.size": 8.0,
	"axes.titlesize": 10.0,
	"axes.labelsize": 10.0,
	"xtick.labelsize": 6.0,
	"ytick.labelsize": 6.0,
	"legend.fontsize": 8.0,
	"figure.dpi": 300.0,
	"savefig.dpi": 300.0,
	"text.usetex": True     # render all text with TeX
})
from matplotlib import figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from optparse import OptionParser
import re

from sphradiometer import ioutils, plotutils
from sphradiometer import healpix as sphhealpix


#
# =============================================================================
#
#                                 Command Line
#
# =============================================================================
#


class Injection(object):
	def __init__(self, ra, dec):
		self.ra = ra
		self.dec = dec


def parse_command_line():
	parser = OptionParser()
	parser.add_option("--injection-ra-dec", default = [], action = "append", help = "injection right-ascension and declination")
	parser.add_option("--baseline-theta", type = "float", default = math.pi / 2, help = "baseline theta")
	parser.add_option("--baseline-phi", type = "float", default = 0., help = "baseline phi")
	options, filenames = parser.parse_args()

	for n, ra_dec, in enumerate(options.injection_ra_dec):
		ra, dec = ra_dec.split(",")
		options.injection_ra_dec[n] = Injection(float(ra), float(dec))

	return options, filenames


#
# =============================================================================
#
#                                    Plots
#
# =============================================================================
#


options, filenames = parse_command_line()


def load_fits_map(filename):
	return sphhealpix.read_fits_healpy_map(filename)

# version for alms
#def load_fits_map(filename):
#	return sphhealpix.healpy_alm_to_map(*sphhealpix.read_fits_healpy_alm(filename))


filename_pattern = re.compile(r"tests_(?P<name>\S+)_(?P<N_T>\S+)_(?P<l_T>\S+)_(?P<l_xi>\S+)_(?P<gmst>[0-9.]+).fits")
for filename in filenames:
	name, N_T_str, l_T_str, l_xi_str, gmst_str = re.search(filename_pattern, filename).groups()
	if name != "exact":
		continue
	N_T = int(N_T_str)
	l_T = int(l_T_str)
	l_xi = int(l_xi_str)
	gmst = float(gmst_str)
	print(filename)


	# Load data
	exact = load_fits_map(filename)
	template = "tests_%%s_%s_%s_%s_%s.%%s" % (N_T_str, l_T_str, l_xi_str, gmst_str)
	fdaverg = load_fits_map(template % ("fdaverage", "fits"))
	tdaverg = load_fits_map(template % ("tdaverage", "fits"))


	# Mollweid projection
	fig = figure.Figure()
	FigureCanvas(fig)
	fig.set_size_inches(5.1, 3.4)

	plot = plotutils.SkyPlot(fig.add_axes((0., 2./3., 2./5., 1./3.)))
	plot.healpix_map_contourf(tdaverg[-1])

	plot = plotutils.SkyPlot(fig.add_axes((0., 1./3., 2./5., 1./3.)))
	plot.healpix_map_contourf(fdaverg[-1])

	plot = plotutils.SkyPlot(fig.add_axes((0., 0., 2./5., 1./3.)))
	plot.healpix_map_contourf(exact[-1])


	# x-y plane
	plot = plotutils.XYSlicePlot(fig.add_axes((2./5., 0., 3./5., 1.), polar = True))

	plot.plot_yvals(plot.yvals_from_healpix_map(exact[-1]) + 1, "k--", linewidth = 0.8)
	plot.plot_yvals(plot.yvals_from_healpix_map(fdaverg[-1]) + 1, "k", linewidth = 0.8)
	plot.axes.set_rgrids((0.0, 0.5, 1.0, 1.5, 2.0, 2.5), ("-1", "", "0", "", "+1", ""))
	#plot.axes.set_thetagrids(range(0, 360, 30), frac = 1.2)

	template = "tests_%s_%s_%s_%s.%%s" % (N_T_str, l_T_str, l_xi_str, gmst_str.replace(".", "_"))
	fig.savefig(template % "png")
	#fig.savefig(template % "svg")
